name: employee_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  carousel_slider: ^4.0.0
  cloud_functions: ^3.2.4
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.14.0
  dots_indicator: ^2.0.0
  dotted_border: ^2.0.0+2
  dotted_line: ^3.1.0
  dropdown_button2: ^1.1.1
  firebase: ^9.0.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.0.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.4
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  http: ^0.13.4
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  intl: ^0.17.0
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  open_file: ^3.2.1
  path_provider: ^2.0.9
  provider: ^6.0.2
  rive: ^0.8.4
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
